### ISSUE TITLE
Typing Mistake

### ISSUE THREAD

**Issue by BotDeveloper002** [Senura2007/Netflix-Clone#1]
There's a typing mistake in the FAQ section. In the second accordion "How much does _Netflic_ cost?". Replace the word "**Netflic**" with "**Netflix**".

![Capture](https://user-images.githubusercontent.com/87744876/131228574-2f2bacc6-ee1e-4684-9897-e7b7d3409fb6.JPG)

**Comment by Senura2007** [comment]
Oh Thanks. I'll fix it
